### ISSUE TITLE
firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [maniakevin/PracticasSistemasReferenciados#3]
Hola @maniakevin no me registra los productos, checalo
![Captura de Pantalla 2020-03-12 a la(s) 21 15 54](https://user-images.githubusercontent.com/14998558/76586549-bc9d5e00-64a6-11ea-80f5-29941e37365c.png)

**Comment by grupohernandezalba** [comment]
Si ya quedo Kevin, solo agrega una liga a tu index, por ahi se ve una letra A que esta volando en tu index.

![Captura de Pantalla 2020-03-13 a la(s) 10 05 22](https://user-images.githubusercontent.com/14998558/76638602-52ba9e00-6512-11ea-9090-9f1739d3f526.png)

**Comment by maniakevin** [comment]
ya registra y ya no esta la A

**Comment by grupohernandezalba** [comment]
Muy bien Kevin.
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
23/03/20
17:11:13
